I've updated the README with some more examples.
JSteunou/marionette.morphdom pull request #2
Opened 2017-06-03 13:09 UTC by scott-w

I've also simplified the Q&A and put everything in a clear header structure.

Let me know what you think and any changes you'd like me to make.

2017-06-03 20:45 UTC, JSteunou commented
I did a little review comments, but WOW what a great re-wording! Thank you so much @scott-w !

2017-06-27 08:25 UTC, JSteunou requested changes

2017-06-27 08:25 UTC, JSteunou commented on README.md
> +rendering functions with [morphdom][morphdom-gh].
Ho I did not know about that syntax. Did github automatically link for project github page?

2017-06-27 08:25 UTC, JSteunou commented on README.md
I would like to keep the "diffing & patching" expression because that is what morphdom does under the hood and I think people are now familiar with this term, thanks to react & react like

2017-06-27 08:25 UTC, JSteunou commented on README.md
> +entire view before it can patch it. Depending on the size of your views, this
This mixin must render the entire view, not Morphdom. I would not introduce confusion

2017-06-27 08:40 UTC, scott-w commented on README.md
> +rendering functions with [morphdom][morphdom-gh].
No, you have to put the link at the bottom of the file:

```markdown
morphdom-gh: https://github.com/...
```

2017-06-27 08:41 UTC, scott-w commented on README.md
> +entire view before it can patch it. Depending on the size of your views, this
So by "this mixin" you're referring to stickit?

2017-06-27 08:43 UTC, JSteunou commented on README.md
> +rendering functions with [morphdom][morphdom-gh].
Ah ok, I did know about this syntax

2017-06-27 08:45 UTC, JSteunou commented on README.md
> +entire view before it can patch it. Depending on the size of your views, this
Nope, marionette.morphdom. This plugin call to render, but morphdom just do patch.

Morphdom (and you miss the *h*) is the lib under it. I must be careful not to confuse people marionette.morphdom !== morphdom

2017-06-27 09:00 UTC, scott-w commented on README.md
> +entire view before it can patch it. Depending on the size of your views, this
Ahh, I see. I'll update it to say `marionette.morphdom` :+1:

2017-07-05 09:10 UTC, JSteunou approved these changes

2017-07-05 09:11 UTC, merged